### ISSUE TITLE
Nothing working 

### ISSUE THREAD

**Issue by ahmadhasankhan** [Aufree/easy-emoji#1]
Hey i have followed instructions but it seems not working for me.

Could you please confirm if its compatible with Rails 4.2.4 ?

**Comment by Aufree** [comment]
Hi, @ahmadhasankhan This project is closed, If you want to use emoji in your rails app, you can try to use [Emojify](https://github.com/Ranks/emojify.js) and [textcomplete](https://github.com/yuku-t/jquery-textcomplete). Thanks for your support.
